### ISSUE TITLE
Parameter limits do not affect fitted quantiles and cumulative probabilities in elicit()

### ISSUE THREAD

**Issue by bjoernholzhauer** [OakleyJ/SHELF#6]
When running the shiny app via `elicit()`, and specifying parameter limits, these seem to not be reflected in the fitted feedback quantiles and cumulative probabilities. Example:
* Parameter limits: 23, 100 
* Elicited judgements
 * Parameter values 25, 50, 75
 * Cumulative probabilities 0.25, 0.5, 0.75
* Distribution Normal
* Feedback quantiles 0.1, 0.9
* Feedback probabilities 20, 30, 90, 100,125
gets me as suggested distribution of a truncated N(mean=50, SD=37.1).

quantiles | values
-- | --
0.10 | 2.50
0.90 | 97.50

and

values | probabilities
-- | --
20.00 | 0.21
30.00 | 0.29
90.00 | 0.86
100.00 | 0.91
125.00 | 0.98

Should this not be based on the truncated distribution on [23, 100] ? It does not change if all the values I ask for are within the parameter limits.

Should the quantiles and probabilities not work something like this (example code for the normal distribution without any real checks for dubious user inputs, no implementation of lower.tail etc. - I assume this would essentially work the same way for all the other distributions):
```
pnorm_trunc = function(q, mean, sd, lower, upper){
  denom = 1-pnorm(lower,mean,sd,lower.tail=T)-pnorm(upper,mean,sd,lower.tail = F)
  return( (pnorm(q,mean,sd,lower.tail=T) - pnorm(lower,mean,sd,lower.tail=T)) / denom )
}
# Test that this works as expected:
pnorm_trunc(x=30, mean=50, sd=37.1, lower=23, upper=100)
samples = rnorm(10000000, 50, 37.1)
length(samples[samples>23 & samples<=30]) / length(samples[samples>23 & samples<100])

qnorm_trunc = function(p, mean, sd, lower, upper){
  padjust = pnorm(q=lower, mean=mean, sd=sd) + p*(pnorm(q=upper, mean=mean, sd=sd) - pnorm(q=lower, mean=mean, sd=sd))
  return( qnorm(padjust, mean=mean, sd=sd) )
}
# Test that this works as expected:
mymedian = qnorm_trunc(0.5, mean=50, sd=37.1, lower=23, upper=100)
mymedian
pnorm_trunc(x=mymedian, mean=50, sd=37.1, lower=23, upper=100)
samples = rnorm(10000000, 50, 37.1)
length(samples[samples>23 & samples<=mymedian]) / length(samples[samples>23 & samples<100])
```

**Comment by OakleyJ** [comment]
Actually, the parameter limits are ignored by the normal and t-distribution fits! The gamma, log normal and log-t fits use the lower limit, and the beta uses both. So if you want something truncated at both ends, the only option currently is a (scaled) beta distribution.

**Comment by bjoernholzhauer** [comment]
The more I think about this, the more I think this is not right. Is the goal not that we have feedback quantiles / probabilities that we can immediately run past the experts? But without the truncation, are they not wrong?

**Comment by OakleyJ** [comment]
If you want hard lower and upper limits, and you use the fitted beta distribution, then you do get a distribution that is constrained to have support only within the limits in the way that you want. 

I think the question here is really, "Is it possible to fit truncated normal distributions, truncated t-distributions, truncated gamma distributions etc. in addition to the normal, t, gamma etc?"

Since this discussion started, I have added three negatively skewed distributions with hard upper limits ("mirror" versions of gamma, lognormal, and log t). I might get round to adding truncated distributions as well, but I think one can usually manage without them:

- The beta family is pretty flexible.
- Sometimes truncating won't make a difference anyway, if sufficient mass is given well within the limits
- Parameter limits aren't always intended to be hard physical limits. They may just represent a "plausible range" (that is actually the intention in SHELF); probability outside these limits is small but not necessarily 0. Or they may just give a sensible range over which we plot a density function.
